/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.ui;

/**
 *
 * @author Lachgar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents(); 
        this.setTitle("Gestion des clients");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        GestionMenu = new javax.swing.JMenu();
        serviceMenuItem = new javax.swing.JMenuItem();
        clientMenuItem = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        SearchServiceMenu = new javax.swing.JMenu();
        searchserviceMenuItem = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GestionMenu.setMnemonic('e');
        GestionMenu.setText("Gestion");

        serviceMenuItem.setMnemonic('t');
        serviceMenuItem.setText("Service");
        serviceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(serviceMenuItem);

        clientMenuItem.setMnemonic('y');
        clientMenuItem.setText("Client");
        clientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(clientMenuItem);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        GestionMenu.add(fileMenu);

        menuBar.add(GestionMenu);

        SearchServiceMenu.setMnemonic('h');
        SearchServiceMenu.setText("Search");

        searchserviceMenuItem.setMnemonic('c');
        searchserviceMenuItem.setText("Service");
        searchserviceMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchserviceMenuItemMouseClicked(evt);
            }
        });
        searchserviceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchserviceMenuItemActionPerformed(evt);
            }
        });
        SearchServiceMenu.add(searchserviceMenuItem);

        menuBar.add(SearchServiceMenu);

        helpMenu1.setMnemonic('h');
        helpMenu1.setText("Help");

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("Contents");
        helpMenu1.add(contentMenuItem1);

        aboutMenuItem1.setMnemonic('a');
        aboutMenuItem1.setText("About");
        helpMenu1.add(aboutMenuItem1);

        menuBar.add(helpMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void serviceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceMenuItemActionPerformed
        // TODO add your handling code here:
        ServiceForm sf = new ServiceForm();
        desktopPane.add(sf);
        sf.setVisible(true);
    }//GEN-LAST:event_serviceMenuItemActionPerformed

    private void searchserviceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchserviceMenuItemActionPerformed
        SearchForm re = new SearchForm();
        desktopPane.add(re);
        re.setVisible(true);
    }//GEN-LAST:event_searchserviceMenuItemActionPerformed

    private void clientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientMenuItemActionPerformed
        ClientForm cf = new ClientForm() ;
        desktopPane.add(cf) ;
        cf.setVisible(true);
    }//GEN-LAST:event_clientMenuItemActionPerformed

    private void searchserviceMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchserviceMenuItemMouseClicked

    }//GEN-LAST:event_searchserviceMenuItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GestionMenu;
    private javax.swing.JMenu SearchServiceMenu;
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem clientMenuItem;
    private javax.swing.JMenuItem contentMenuItem1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem searchserviceMenuItem;
    private javax.swing.JMenuItem serviceMenuItem;
    // End of variables declaration//GEN-END:variables

}
